# Generated by Django 5.2.7 on 2025-10-28 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat_no', models.CharField(db_index=True, help_text='e.g., SEAT-101', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Seat No must be in format SEAT-101', regex='^SEAT-\\d+$')])),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?[0-9\\s\\-\\(\\)]+$')])),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('print_status', models.CharField(choices=[('not_printed', 'Not Printed'), ('printed', 'Printed')], db_index=True, default='not_printed', max_length=20)),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'ordering': ['seat_no'],
                'indexes': [models.Index(fields=['seat_no'], name='seatalignme_seat_no_c98cba_idx'), models.Index(fields=['email'], name='seatalignme_email_9fe232_idx'), models.Index(fields=['print_status'], name='seatalignme_print_s_601cb1_idx')],
            },
        ),
    ]
