# Generated by Django 5.2.7 on 2025-10-29 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatalignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatCSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='seat_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('processed', models.BooleanField(default=False)),
                ('processed_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('duplicate_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Seat CSV Upload',
                'verbose_name_plural': 'Seat CSV Uploads',
            },
        ),
    ]
