# Generated by Django 5.2.7 on 2025-10-29 16:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatalignment', '0002_seatcsvupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Seat Template', help_text='Name of the template (e.g., Conference 2025)', max_length=100)),
                ('position_x', models.PositiveIntegerField(default=20, help_text='X offset in pixels', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('position_y', models.PositiveIntegerField(default=20, help_text='Y offset in pixels', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('font_size', models.PositiveIntegerField(default=24, help_text='Font size in pixels', validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(100)])),
                ('is_bold', models.BooleanField(default=False)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('page_width_mm', models.PositiveIntegerField(default=105, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)])),
                ('page_height_mm', models.PositiveIntegerField(default=148, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge Template',
                'verbose_name_plural': 'Badge Templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
