# Generated by Django 5.2.7 on 2025-10-30 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('seats', 'Manage Seats'), ('badges', 'Print Badges'), ('users', 'User Management'), ('alignment', 'Badge Alignment')], max_length=20)),
                ('action', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('delete', 'Delete'), ('print', 'Print'), ('export', 'Export'), ('create', 'Create'), ('reset', 'Reset')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.user')),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'indexes': [models.Index(fields=['user', 'module'], name='accounts_us_user_id_eb0769_idx')],
                'unique_together': {('user', 'module', 'action')},
            },
        ),
    ]
