# Generated by Django 5.2.7 on 2025-10-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('delete', 'Delete'), ('print', 'Print'), ('export', 'Export'), ('create', 'Create'), ('upload', 'Upload'), ('reset', 'Reset')], max_length=20),
        ),
    ]
